version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: uaq_eventhub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uaq_user
      POSTGRES_PASSWORD: uaq_password
      POSTGRES_DB: uaq_eventhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
